import { Search2Icon } from "@chakra-ui/icons";
import {
  Box,
  VStack,
  Text,
  HStack,
  Input,
  Switch,
  keyframes,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/Home.module.css";
import { motion } from "framer-motion";
import withTransition from "@components/withTransition";
import { useState } from "react";

const animationKeyframes = keyframes`
0% {
    transform: rotate3d(0, 0, 1, 0deg);
  }
  25% {
    transform: rotate3d(0, 0, 1, 90deg);
  }
  50% {
    transform: rotate3d(0, 0, 1, 180deg);
  }
  75% {
    transform: rotate3d(0, 0, 1, 270deg);
  }
  100% {
    transform: rotate3d(0, 0, 1, 360deg);
  }
`;

const animation = `${animationKeyframes} 30s normal linear infinite`;

const Home: NextPage = () => {
  const [isGraphView, setIsGraphView] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Telescope: Ethereum Transaction Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack className={styles.titleContainer}>
        <Text className={styles.title}>TELESCOPE</Text>
        <Text className={styles.subtitle}>Ethereum Transaction Explorer</Text>
        <HStack className={styles.searchbar}>
          <Search2Icon color="white" />
          <Input
            className={styles.searchInput}
            placeholder="Search by Address /Txn Hash / Block / Token / ENS"
          />
          <HStack className={styles.switchContainer}>
            <Switch
              colorScheme="orange"
              onChange={() => {
                setIsGraphView(!isGraphView);
              }}
              className={
                isGraphView ? styles.isGraphView : styles.isNotGraphView
              }
            />
            <Text className={styles.graphViewLabel}>Graph View</Text>
          </HStack>
        </HStack>
      </VStack>
      <Box className={styles.ellipseOne}></Box>
      <Box className={styles.ellipseTwo}></Box>
      <Box className={styles.ethereumLogoContainer}>
        <Box
          className={styles.ethereumLogo}
          as={motion.div}
          animation={animation}
          bgImage="/eth.png"
        />
      </Box>
    </div>
  );
};

export default withTransition(Home);
